drop schema IF EXISTS photo_share CASCADE;

CREATE SCHEMA IF NOT EXISTS photo_share;
SET search_path TO photo_share;

DROP TABLE IF EXISTS PERSON CASCADE;

CREATE TABLE PERSON (
    ID INTEGER NOT NULL,
    USER_NAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL
);
